server {
    listen 80;

    # React 静态文件
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # 代理 API 请求到后端容器（服务名 backend）
    location /api/ {
        proxy_pass http://market-monitor:8090;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
